name: Docker Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and test
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: maitri-app:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test container health
      run: |
        docker run -d --name maitri-test -p 3001:3001 -e NODE_ENV=test maitri-app:test
        sleep 10
        docker ps
        wget --spider --quiet http://localhost:3001/health || exit 1
        docker stop maitri-test
    
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/maitri-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 